{
  "cve": "CVE-2023-26151",
  "mitre": {
    "cpes": [],
    "created": "2023-10-03T05:00:01.093000+00:00",
    "description": "Versions of the package asyncua before 0.9.96 are vulnerable to Denial of Service (DoS) such that an attacker can send a malformed packet and as a result, the server will enter into an infinite loop and consume excessive memory.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 5.3,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L/E:P"
      },
      "cvssV4_0": {}
    },
    "mitre_repo_path": "cves/2023/26xxx/CVE-2023-26151.json",
    "references": [
      "https://gist.github.com/artfire52/1540b234350795e0ecb4d672608dbec8",
      "https://github.com/FreeOpcUa/opcua-asyncio/commit/f6603daa34a93a658f0e176cb0b9ee5a6643b262",
      "https://github.com/FreeOpcUa/opcua-asyncio/issues/1013",
      "https://github.com/FreeOpcUa/opcua-asyncio/pull/1039",
      "https://github.com/FreeOpcUa/opcua-asyncio/releases/tag/v0.9.96",
      "https://security.snyk.io/vuln/SNYK-PYTHON-ASYNCUA-5673709"
    ],
    "title": null,
    "updated": "2024-08-02T11:39:06.637000+00:00",
    "vendors": [],
    "weaknesses": [
      "CWE-400"
    ]
  },
  "nvd": {
    "cpes": [
      "cpe:2.3:a:freeopcua:opcua-asyncio:*:*:*:*:*:python:*:*"
    ],
    "created": "2023-10-03T05:15:50.507000+00:00",
    "description": "Versions of the package asyncua before 0.9.96 are vulnerable to Denial of Service (DoS) such that an attacker can send a malformed packet and as a result, the server will enter into an infinite loop and consume excessive memory.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 7.5,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
      },
      "cvssV4_0": {}
    },
    "nvd_repo_path": "2023/CVE-2023-26151.json",
    "references": [
      "https://gist.github.com/artfire52/1540b234350795e0ecb4d672608dbec8",
      "https://github.com/FreeOpcUa/opcua-asyncio/commit/f6603daa34a93a658f0e176cb0b9ee5a6643b262",
      "https://github.com/FreeOpcUa/opcua-asyncio/issues/1013",
      "https://github.com/FreeOpcUa/opcua-asyncio/pull/1039",
      "https://github.com/FreeOpcUa/opcua-asyncio/releases/tag/v0.9.96",
      "https://security.snyk.io/vuln/SNYK-PYTHON-ASYNCUA-5673709"
    ],
    "title": null,
    "updated": "2023-11-07T04:09:29.060000+00:00",
    "vendors": [
      "freeopcua",
      "freeopcua$PRODUCT$opcua-asyncio"
    ],
    "weaknesses": [
      "CWE-400",
      "CWE-835"
    ]
  },
  "opencve": {
    "changes": [],
    "cpes": {
      "data": [
        "cpe:2.3:a:freeopcua:opcua-asyncio:*:*:*:*:*:python:*:*"
      ],
      "providers": [
        "nvd"
      ]
    },
    "created": {
      "data": "2023-10-03T05:00:01.093000+00:00",
      "provider": "mitre"
    },
    "description": {
      "data": "Versions of the package asyncua before 0.9.96 are vulnerable to Denial of Service (DoS) such that an attacker can send a malformed packet and as a result, the server will enter into an infinite loop and consume excessive memory.",
      "provider": "mitre"
    },
    "metrics": {
      "cvssV2_0": {
        "data": {},
        "provider": null
      },
      "cvssV3_0": {
        "data": {},
        "provider": null
      },
      "cvssV3_1": {
        "data": {
          "score": 5.3,
          "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L/E:P"
        },
        "provider": "mitre"
      },
      "cvssV4_0": {
        "data": {},
        "provider": null
      },
      "kev": {
        "data": {},
        "provider": null
      },
      "ssvc": {
        "data": {},
        "provider": null
      },
      "threat_severity": {
        "data": null,
        "provider": null
      }
    },
    "references": {
      "data": [
        "https://gist.github.com/artfire52/1540b234350795e0ecb4d672608dbec8",
        "https://github.com/FreeOpcUa/opcua-asyncio/commit/f6603daa34a93a658f0e176cb0b9ee5a6643b262",
        "https://github.com/FreeOpcUa/opcua-asyncio/issues/1013",
        "https://github.com/FreeOpcUa/opcua-asyncio/pull/1039",
        "https://github.com/FreeOpcUa/opcua-asyncio/releases/tag/v0.9.96",
        "https://security.snyk.io/vuln/SNYK-PYTHON-ASYNCUA-5673709"
      ],
      "providers": [
        "mitre",
        "nvd"
      ]
    },
    "title": {
      "data": null,
      "provider": null
    },
    "updated": {
      "data": "2024-08-02T11:39:06.637000+00:00",
      "provider": "mitre"
    },
    "vendors": {
      "data": [
        "freeopcua",
        "freeopcua$PRODUCT$opcua-asyncio"
      ],
      "providers": [
        "nvd"
      ]
    },
    "weaknesses": {
      "data": [
        "CWE-400",
        "CWE-835"
      ],
      "providers": [
        "mitre",
        "nvd"
      ]
    }
  }
}