{
  "cve": "CVE-2023-6476",
  "mitre": {
    "cpes": [
      "cpe:/a:redhat:openshift:3.11",
      "cpe:/a:redhat:openshift:4.13::el8",
      "cpe:/a:redhat:openshift:4.13::el9",
      "cpe:/a:redhat:openshift:4.14::el8",
      "cpe:/a:redhat:openshift:4.14::el9"
    ],
    "created": "2024-01-09T21:32:03.407000+00:00",
    "description": "A flaw was found in CRI-O that involves an experimental annotation leading to a container being unconfined. This may allow a pod to specify and get any amount of memory/cpu, circumventing the kubernetes scheduler and potentially resulting in a denial of service in the node.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 6.5,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
      },
      "cvssV4_0": {}
    },
    "mitre_repo_path": "cves/2023/6xxx/CVE-2023-6476.json",
    "references": [
      "https://access.redhat.com/errata/RHSA-2024:0195",
      "https://access.redhat.com/errata/RHSA-2024:0207",
      "https://access.redhat.com/security/cve/CVE-2023-6476",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2253994"
    ],
    "title": "Cri-o: pods are able to break out of resource confinement on cgroupv2",
    "updated": "2024-08-20T16:21:15.317000+00:00",
    "vendors": [
      "redhat",
      "redhat$PRODUCT$openshift"
    ],
    "weaknesses": [
      "CWE-770"
    ]
  },
  "nvd": {
    "cpes": [
      "cpe:2.3:a:redhat:openshift_container_platform:3.11:*:*:*:*:*:*:*",
      "cpe:2.3:a:redhat:openshift_container_platform:4.13:*:*:*:*:*:*:*",
      "cpe:2.3:a:redhat:openshift_container_platform:4.14:*:*:*:*:*:*:*",
      "cpe:2.3:o:redhat:enterprise_linux:8.0:*:*:*:*:*:*:*",
      "cpe:2.3:o:redhat:enterprise_linux:9.0:*:*:*:*:*:*:*"
    ],
    "created": "2024-01-09T22:15:43.610000+00:00",
    "description": "A flaw was found in CRI-O that involves an experimental annotation leading to a container being unconfined. This may allow a pod to specify and get any amount of memory/cpu, circumventing the kubernetes scheduler and potentially resulting in a denial of service in the node.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 7.5,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
      },
      "cvssV4_0": {}
    },
    "nvd_repo_path": "2023/CVE-2023-6476.json",
    "references": [
      "https://access.redhat.com/errata/RHSA-2024:0195",
      "https://access.redhat.com/errata/RHSA-2024:0207",
      "https://access.redhat.com/security/cve/CVE-2023-6476",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2253994"
    ],
    "title": null,
    "updated": "2024-02-04T20:15:46.327000+00:00",
    "vendors": [
      "redhat",
      "redhat$PRODUCT$enterprise_linux",
      "redhat$PRODUCT$openshift_container_platform"
    ],
    "weaknesses": [
      "CWE-770"
    ]
  },
  "opencve": {
    "changes": [],
    "cpes": {
      "data": [
        "cpe:/a:redhat:openshift:3.11",
        "cpe:/a:redhat:openshift:4.13::el8",
        "cpe:/a:redhat:openshift:4.13::el9",
        "cpe:/a:redhat:openshift:4.14::el8",
        "cpe:/a:redhat:openshift:4.14::el9",
        "cpe:2.3:a:redhat:openshift_container_platform:3.11:*:*:*:*:*:*:*",
        "cpe:2.3:a:redhat:openshift_container_platform:4.13:*:*:*:*:*:*:*",
        "cpe:2.3:a:redhat:openshift_container_platform:4.14:*:*:*:*:*:*:*",
        "cpe:2.3:o:redhat:enterprise_linux:8.0:*:*:*:*:*:*:*",
        "cpe:2.3:o:redhat:enterprise_linux:9.0:*:*:*:*:*:*:*"
      ],
      "providers": [
        "mitre",
        "nvd",
        "redhat"
      ]
    },
    "created": {
      "data": "2024-01-09T21:00:00+00:00",
      "provider": "redhat"
    },
    "description": {
      "data": "A flaw was found in CRI-O that involves an experimental annotation leading to a container being unconfined. This may allow a pod to specify and get any amount of memory/cpu, circumventing the kubernetes scheduler and potentially resulting in a denial of service in the node.",
      "provider": "mitre"
    },
    "metrics": {
      "cvssV2_0": {
        "data": {},
        "provider": null
      },
      "cvssV3_0": {
        "data": {},
        "provider": null
      },
      "cvssV3_1": {
        "data": {
          "score": 6.5,
          "vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
        },
        "provider": "mitre"
      },
      "cvssV4_0": {
        "data": {},
        "provider": null
      },
      "kev": {
        "data": {},
        "provider": null
      },
      "ssvc": {
        "data": {},
        "provider": null
      },
      "threat_severity": {
        "data": "Moderate",
        "provider": "redhat"
      }
    },
    "references": {
      "data": [
        "https://access.redhat.com/errata/RHSA-2024:0195",
        "https://access.redhat.com/errata/RHSA-2024:0207",
        "https://access.redhat.com/security/cve/CVE-2023-6476",
        "https://bugzilla.redhat.com/show_bug.cgi?id=2253994",
        "https://nvd.nist.gov/vuln/detail/CVE-2023-6476",
        "https://www.cve.org/CVERecord?id=CVE-2023-6476"
      ],
      "providers": [
        "mitre",
        "nvd",
        "redhat"
      ]
    },
    "title": {
      "data": "Cri-o: pods are able to break out of resource confinement on cgroupv2",
      "provider": "mitre"
    },
    "updated": {
      "data": "2024-08-20T16:21:15.317000+00:00",
      "provider": "mitre"
    },
    "vendors": {
      "data": [
        "redhat",
        "redhat$PRODUCT$enterprise_linux",
        "redhat$PRODUCT$openshift",
        "redhat$PRODUCT$openshift_container_platform"
      ],
      "providers": [
        "mitre",
        "nvd",
        "redhat"
      ]
    },
    "weaknesses": {
      "data": [
        "CWE-770"
      ],
      "providers": [
        "mitre",
        "nvd",
        "redhat"
      ]
    }
  },
  "redhat": {
    "cpes": [
      "cpe:/a:redhat:openshift:4.13::el8",
      "cpe:/a:redhat:openshift:4.14::el8"
    ],
    "created": "2024-01-09T21:00:00+00:00",
    "description": "A flaw was found in CRI-O that involves an experimental annotation leading to a container being unconfined. This may allow a pod to specify and get any amount of memory/cpu, circumventing the kubernetes scheduler and potentially resulting in a denial of service in the node.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 6.5,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
      },
      "threat_severity": "Moderate"
    },
    "redhat_repo_path": "2023/CVE-2023-6476.json",
    "references": [
      "https://nvd.nist.gov/vuln/detail/CVE-2023-6476",
      "https://www.cve.org/CVERecord?id=CVE-2023-6476"
    ],
    "title": "cri-o: Pods are able to break out of resource confinement on cgroupv2",
    "updated": "2024-01-09T21:00:00+00:00",
    "vendors": [
      "redhat",
      "redhat$PRODUCT$openshift"
    ],
    "weaknesses": [
      "CWE-770"
    ]
  }
}