{
  "cve": "CVE-2023-41040",
  "mitre": {
    "cpes": [],
    "created": "2023-08-30T21:07:42.263000+00:00",
    "description": " GitPython is a python library used to interact with Git repositories. In order to resolve some git references, GitPython reads files from the `.git` directory, in some places the name of the file being read is provided by the user, GitPython doesn't check if this file is located outside the `.git` directory. This allows an attacker to make GitPython read any file from the system. This vulnerability is present in https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175. That code joins the base directory with a user given string without checking if the final path is located outside the base directory. This vulnerability cannot be used to read the contents of files but could in theory be used to trigger a denial of service for the program. This issue has not yet been addressed.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 4,
        "vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L"
      },
      "cvssV4_0": {}
    },
    "mitre_repo_path": "cves/2023/41xxx/CVE-2023-41040.json",
    "references": [
      "https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175",
      "https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-cwvm-v4w8-q58c",
      "https://lists.debian.org/debian-lts-announce/2023/09/msg00036.html"
    ],
    "title": "Blind local file inclusion in GitPython",
    "updated": "2024-08-02T18:46:11.452000+00:00",
    "vendors": [],
    "weaknesses": [
      "CWE-22"
    ]
  },
  "nvd": {
    "cpes": [
      "cpe:2.3:a:gitpython_project:gitpython:*:*:*:*:*:python:*:*"
    ],
    "created": "2023-08-30T22:15:09.857000+00:00",
    "description": " GitPython is a python library used to interact with Git repositories. In order to resolve some git references, GitPython reads files from the `.git` directory, in some places the name of the file being read is provided by the user, GitPython doesn't check if this file is located outside the `.git` directory. This allows an attacker to make GitPython read any file from the system. This vulnerability is present in https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175. That code joins the base directory with a user given string without checking if the final path is located outside the base directory. This vulnerability cannot be used to read the contents of files but could in theory be used to trigger a denial of service for the program. This issue has not yet been addressed.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 6.5,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:L"
      },
      "cvssV4_0": {}
    },
    "nvd_repo_path": "2023/CVE-2023-41040.json",
    "references": [
      "https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175",
      "https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-cwvm-v4w8-q58c",
      "https://lists.debian.org/debian-lts-announce/2023/09/msg00036.html"
    ],
    "title": null,
    "updated": "2023-09-29T20:15:09.880000+00:00",
    "vendors": [
      "gitpython_project",
      "gitpython_project$PRODUCT$gitpython"
    ],
    "weaknesses": [
      "CWE-22"
    ]
  },
  "opencve": {
    "changes": [],
    "cpes": {
      "data": [
        "cpe:/a:redhat:ansible_automation_platform:2.4::el8",
        "cpe:/a:redhat:ansible_automation_platform:2.4::el9",
        "cpe:/a:redhat:openstack:17.1::el8",
        "cpe:/a:redhat:openstack:17.1::el9",
        "cpe:/a:redhat:satellite:6.14::el8",
        "cpe:/a:redhat:satellite_capsule:6.14::el8",
        "cpe:2.3:a:gitpython_project:gitpython:*:*:*:*:*:python:*:*"
      ],
      "providers": [
        "nvd",
        "redhat"
      ]
    },
    "created": {
      "data": "2023-08-30T21:07:42.263000+00:00",
      "provider": "mitre"
    },
    "description": {
      "data": " GitPython is a python library used to interact with Git repositories. In order to resolve some git references, GitPython reads files from the `.git` directory, in some places the name of the file being read is provided by the user, GitPython doesn't check if this file is located outside the `.git` directory. This allows an attacker to make GitPython read any file from the system. This vulnerability is present in https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175. That code joins the base directory with a user given string without checking if the final path is located outside the base directory. This vulnerability cannot be used to read the contents of files but could in theory be used to trigger a denial of service for the program. This issue has not yet been addressed.",
      "provider": "mitre"
    },
    "metrics": {
      "cvssV2_0": {
        "data": {},
        "provider": null
      },
      "cvssV3_0": {
        "data": {},
        "provider": null
      },
      "cvssV3_1": {
        "data": {
          "score": 4,
          "vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L"
        },
        "provider": "mitre"
      },
      "cvssV4_0": {
        "data": {},
        "provider": null
      },
      "kev": {
        "data": {},
        "provider": null
      },
      "ssvc": {
        "data": {},
        "provider": null
      },
      "threat_severity": {
        "data": "Moderate",
        "provider": "redhat"
      }
    },
    "references": {
      "data": [
        "https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175",
        "https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-cwvm-v4w8-q58c",
        "https://lists.debian.org/debian-lts-announce/2023/09/msg00036.html",
        "https://nvd.nist.gov/vuln/detail/CVE-2023-41040",
        "https://www.cve.org/CVERecord?id=CVE-2023-41040"
      ],
      "providers": [
        "mitre",
        "nvd",
        "redhat"
      ]
    },
    "title": {
      "data": "Blind local file inclusion in GitPython",
      "provider": "mitre"
    },
    "updated": {
      "data": "2024-08-02T18:46:11.452000+00:00",
      "provider": "mitre"
    },
    "vendors": {
      "data": [
        "gitpython_project",
        "gitpython_project$PRODUCT$gitpython",
        "redhat",
        "redhat$PRODUCT$ansible_automation_platform",
        "redhat$PRODUCT$openstack",
        "redhat$PRODUCT$satellite",
        "redhat$PRODUCT$satellite_capsule"
      ],
      "providers": [
        "nvd",
        "redhat"
      ]
    },
    "weaknesses": {
      "data": [
        "CWE-22"
      ],
      "providers": [
        "mitre",
        "nvd",
        "redhat"
      ]
    }
  },
  "redhat": {
    "cpes": [
      "cpe:/a:redhat:ansible_automation_platform:2.4::el8",
      "cpe:/a:redhat:ansible_automation_platform:2.4::el9",
      "cpe:/a:redhat:openstack:17.1::el8",
      "cpe:/a:redhat:openstack:17.1::el9",
      "cpe:/a:redhat:satellite:6.14::el8",
      "cpe:/a:redhat:satellite_capsule:6.14::el8"
    ],
    "created": "2023-08-31T00:00:00+00:00",
    "description": "GitPython is a python library used to interact with Git repositories. In order to resolve some git references, GitPython reads files from the `.git` directory, in some places the name of the file being read is provided by the user, GitPython doesn't check if this file is located outside the `.git` directory. This allows an attacker to make GitPython read any file from the system. This vulnerability is present in https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175. That code joins the base directory with a user given string without checking if the final path is located outside the base directory. This vulnerability cannot be used to read the contents of files but could in theory be used to trigger a denial of service for the program. This issue has not yet been addressed.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 5.1,
        "vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:L"
      },
      "threat_severity": "Moderate"
    },
    "redhat_repo_path": "2023/CVE-2023-41040.json",
    "references": [
      "https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-cwvm-v4w8-q58c",
      "https://nvd.nist.gov/vuln/detail/CVE-2023-41040",
      "https://www.cve.org/CVERecord?id=CVE-2023-41040"
    ],
    "title": "GitPython: Blind local file inclusion",
    "updated": "2023-08-31T00:00:00+00:00",
    "vendors": [
      "redhat",
      "redhat$PRODUCT$ansible_automation_platform",
      "redhat$PRODUCT$openstack",
      "redhat$PRODUCT$satellite",
      "redhat$PRODUCT$satellite_capsule"
    ],
    "weaknesses": [
      "CWE-22"
    ]
  }
}