{
  "cve": "CVE-2009-0668",
  "mitre": {
    "cpes": [],
    "created": "2009-08-07T19:00:00+00:00",
    "description": "Unspecified vulnerability in Zope Object Database (ZODB) before 3.8.2, when certain Zope Enterprise Objects (ZEO) database sharing is enabled, allows remote attackers to execute arbitrary Python code via vectors involving the ZEO network protocol.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {},
      "cvssV4_0": {}
    },
    "mitre_repo_path": "cves/2009/0xxx/CVE-2009-0668.json",
    "references": [
      "http://mail.zope.org/pipermail/zope-announce/2009-August/002220.html",
      "http://osvdb.org/56827",
      "http://pypi.python.org/pypi/ZODB3/3.8.2#whats-new-in-zodb-3-8-2",
      "http://secunia.com/advisories/36204",
      "http://secunia.com/advisories/36205",
      "http://www.securityfocus.com/bid/35987",
      "http://www.vupen.com/english/advisories/2009/2217",
      "https://exchange.xforce.ibmcloud.com/vulnerabilities/52377"
    ],
    "title": null,
    "updated": "2017-08-16T14:57:01+00:00",
    "vendors": [],
    "weaknesses": []
  },
  "nvd": {
    "cpes": [
      "cpe:2.3:a:zope:zodb:*:*:*:*:*:*:*:*",
      "cpe:2.3:a:zope:zodb:2.10.9:*:*:*:*:*:*:*",
      "cpe:2.3:a:zope:zodb:2.11.4:*:*:*:*:*:*:*",
      "cpe:2.3:a:zope:zodb:2.8.11:*:*:*:*:*:*:*",
      "cpe:2.3:a:zope:zodb:2.9.11:*:*:*:*:*:*:*",
      "cpe:2.3:a:zope:zodb:3.1.1:*:*:*:*:*:*:*",
      "cpe:2.3:a:zope:zodb:3.1:*:*:*:*:*:*:*",
      "cpe:2.3:a:zope:zodb:3.2.4:*:*:*:*:*:*:*",
      "cpe:2.3:a:zope:zodb:3.2:*:*:*:*:*:*:*",
      "cpe:2.3:a:zope:zodb:3.3.3:*:*:*:*:*:*:*",
      "cpe:2.3:a:zope:zodb:3.3:*:*:*:*:*:*:*",
      "cpe:2.3:a:zope:zodb:3.4.1:*:*:*:*:*:*:*",
      "cpe:2.3:a:zope:zodb:3.4:*:*:*:*:*:*:*",
      "cpe:2.3:a:zope:zodb:3.5:*:*:*:*:*:*:*",
      "cpe:2.3:a:zope:zodb:3.6:*:*:*:*:*:*:*",
      "cpe:2.3:a:zope:zodb:3.7:*:*:*:*:*:*:*",
      "cpe:2.3:a:zope:zodb:3.8.0:*:*:*:*:*:*:*"
    ],
    "created": "2009-08-07T19:30:00.203000+00:00",
    "description": "Unspecified vulnerability in Zope Object Database (ZODB) before 3.8.2, when certain Zope Enterprise Objects (ZEO) database sharing is enabled, allows remote attackers to execute arbitrary Python code via vectors involving the ZEO network protocol.",
    "metrics": {
      "cvssV2_0": {
        "score": 6.5,
        "vector": "AV:N/AC:L/Au:S/C:P/I:P/A:P"
      },
      "cvssV3_0": {},
      "cvssV3_1": {},
      "cvssV4_0": {}
    },
    "nvd_repo_path": "2009/CVE-2009-0668.json",
    "references": [
      "http://mail.zope.org/pipermail/zope-announce/2009-August/002220.html",
      "http://osvdb.org/56827",
      "http://pypi.python.org/pypi/ZODB3/3.8.2#whats-new-in-zodb-3-8-2",
      "http://secunia.com/advisories/36204",
      "http://secunia.com/advisories/36205",
      "http://www.securityfocus.com/bid/35987",
      "http://www.vupen.com/english/advisories/2009/2217",
      "https://exchange.xforce.ibmcloud.com/vulnerabilities/52377"
    ],
    "title": null,
    "updated": "2017-08-17T01:29:58.193000+00:00",
    "vendors": [
      "zope",
      "zope$PRODUCT$zodb"
    ],
    "weaknesses": [
      "CWE-94",
      "NVD-CWE-noinfo"
    ]
  },
  "opencve": {
    "changes": [],
    "cpes": {
      "data": [
        "cpe:2.3:a:zope:zodb:*:*:*:*:*:*:*:*",
        "cpe:2.3:a:zope:zodb:2.10.9:*:*:*:*:*:*:*",
        "cpe:2.3:a:zope:zodb:2.11.4:*:*:*:*:*:*:*",
        "cpe:2.3:a:zope:zodb:2.8.11:*:*:*:*:*:*:*",
        "cpe:2.3:a:zope:zodb:2.9.11:*:*:*:*:*:*:*",
        "cpe:2.3:a:zope:zodb:3.1.1:*:*:*:*:*:*:*",
        "cpe:2.3:a:zope:zodb:3.1:*:*:*:*:*:*:*",
        "cpe:2.3:a:zope:zodb:3.2.4:*:*:*:*:*:*:*",
        "cpe:2.3:a:zope:zodb:3.2:*:*:*:*:*:*:*",
        "cpe:2.3:a:zope:zodb:3.3.3:*:*:*:*:*:*:*",
        "cpe:2.3:a:zope:zodb:3.3:*:*:*:*:*:*:*",
        "cpe:2.3:a:zope:zodb:3.4.1:*:*:*:*:*:*:*",
        "cpe:2.3:a:zope:zodb:3.4:*:*:*:*:*:*:*",
        "cpe:2.3:a:zope:zodb:3.5:*:*:*:*:*:*:*",
        "cpe:2.3:a:zope:zodb:3.6:*:*:*:*:*:*:*",
        "cpe:2.3:a:zope:zodb:3.7:*:*:*:*:*:*:*",
        "cpe:2.3:a:zope:zodb:3.8.0:*:*:*:*:*:*:*"
      ],
      "providers": [
        "nvd"
      ]
    },
    "created": {
      "data": "2009-08-06T00:00:00+00:00",
      "provider": "redhat"
    },
    "description": {
      "data": "Unspecified vulnerability in Zope Object Database (ZODB) before 3.8.2, when certain Zope Enterprise Objects (ZEO) database sharing is enabled, allows remote attackers to execute arbitrary Python code via vectors involving the ZEO network protocol.",
      "provider": "mitre"
    },
    "metrics": {
      "cvssV2_0": {
        "data": {
          "score": 6.5,
          "vector": "AV:N/AC:L/Au:S/C:P/I:P/A:P"
        },
        "provider": "nvd"
      },
      "cvssV3_0": {
        "data": {},
        "provider": null
      },
      "cvssV3_1": {
        "data": {},
        "provider": null
      },
      "cvssV4_0": {
        "data": {},
        "provider": null
      },
      "kev": {
        "data": {},
        "provider": null
      },
      "ssvc": {
        "data": {},
        "provider": null
      },
      "threat_severity": {
        "data": "Important",
        "provider": "redhat"
      }
    },
    "references": {
      "data": [
        "http://mail.zope.org/pipermail/zope-announce/2009-August/002220.html",
        "http://osvdb.org/56827",
        "http://pypi.python.org/pypi/ZODB3/3.8.2#whats-new-in-zodb-3-8-2",
        "http://secunia.com/advisories/36204",
        "http://secunia.com/advisories/36205",
        "http://www.securityfocus.com/bid/35987",
        "http://www.vupen.com/english/advisories/2009/2217",
        "https://exchange.xforce.ibmcloud.com/vulnerabilities/52377",
        "https://nvd.nist.gov/vuln/detail/CVE-2009-0668",
        "https://www.cve.org/CVERecord?id=CVE-2009-0668"
      ],
      "providers": [
        "mitre",
        "nvd",
        "redhat"
      ]
    },
    "title": {
      "data": "zope: ZEO arbitrary Python code execution in the context of server process",
      "provider": "nvd"
    },
    "updated": {
      "data": "2017-08-17T01:29:58.193000+00:00",
      "provider": "nvd"
    },
    "vendors": {
      "data": [
        "zope",
        "zope$PRODUCT$zodb"
      ],
      "providers": [
        "nvd"
      ]
    },
    "weaknesses": {
      "data": [
        "CWE-94",
        "NVD-CWE-noinfo"
      ],
      "providers": [
        "nvd"
      ]
    }
  },
  "redhat": {
    "cpes": [],
    "created": "2009-08-06T00:00:00+00:00",
    "description": "Unspecified vulnerability in Zope Object Database (ZODB) before 3.8.2, when certain Zope Enterprise Objects (ZEO) database sharing is enabled, allows remote attackers to execute arbitrary Python code via vectors involving the ZEO network protocol.",
    "metrics": {
      "cvssV2_0": {
        "score": 6.3,
        "vector": "AV:N/AC:M/Au:S/C:N/I:C/A:N"
      },
      "cvssV3_0": {},
      "cvssV3_1": {},
      "threat_severity": "Important"
    },
    "redhat_repo_path": "2009/CVE-2009-0668.json",
    "references": [
      "https://nvd.nist.gov/vuln/detail/CVE-2009-0668",
      "https://www.cve.org/CVERecord?id=CVE-2009-0668"
    ],
    "title": "zope: ZEO arbitrary Python code execution in the context of server process",
    "updated": "2009-08-06T00:00:00+00:00",
    "vendors": [],
    "weaknesses": []
  }
}