{
  "cve": "CVE-2024-35326",
  "mitre": {
    "cpes": [],
    "created": "2024-06-13T00:00:00+00:00",
    "description": "DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: none. Reason: This candidate was withdrawn by its CNA. Further investigation showed that it was not a security issue. Notes: none.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {},
      "cvssV4_0": {}
    },
    "mitre_repo_path": "cves/2024/35xxx/CVE-2024-35326.json",
    "references": [],
    "title": null,
    "updated": "2024-08-28T15:38:17.799524+00:00",
    "vendors": [],
    "weaknesses": []
  },
  "nvd": {
    "cpes": [],
    "created": "2024-06-13T17:15:50.490000+00:00",
    "description": "Rejected reason: DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: none. Reason: This candidate was withdrawn by its CNA. Further investigation showed that it was not a security issue. Notes: none.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {},
      "cvssV4_0": {}
    },
    "nvd_repo_path": "2024/CVE-2024-35326.json",
    "references": [],
    "title": null,
    "updated": "2024-08-28T16:15:08.740000+00:00",
    "vendors": [],
    "weaknesses": []
  },
  "opencve": {
    "changes": [
      {
        "created": "2024-08-06T17:15:00+00:00",
        "data": [
          {
            "details": [
              "pyyaml",
              "pyyaml$PRODUCT$libyaml"
            ],
            "type": "first_time"
          },
          {
            "details": {
              "added": [
                "CWE-787"
              ],
              "removed": []
            },
            "type": "weaknesses"
          },
          {
            "details": {
              "added": [
                "cpe:2.3:a:pyyaml:libyaml:0.2.5:*:*:*:*:*:*:*"
              ],
              "removed": []
            },
            "type": "cpes"
          },
          {
            "details": {
              "added": [
                "pyyaml",
                "pyyaml$PRODUCT$libyaml"
              ],
              "removed": []
            },
            "type": "vendors"
          },
          {
            "details": {
              "added": {},
              "removed": {},
              "updated": {
                "cvssV3_1": {
                  "new": {
                    "score": 9.8,
                    "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
                  },
                  "old": {
                    "score": 6.5,
                    "vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
                  }
                }
              }
            },
            "type": "metrics"
          }
        ],
        "id": "7dd6ea64-c704-4216-85ac-d94ee4741742"
      },
      {
        "created": "2024-08-28T14:30:00+00:00",
        "data": [
          {
            "details": {
              "added": [
                "https://github.com/idhyt/pocs/tree/main/libyaml"
              ],
              "removed": []
            },
            "type": "references"
          }
        ],
        "id": "9bf56f00-7b0d-4c25-bec3-70849b1de595"
      },
      {
        "created": "2024-08-28T14:45:00+00:00",
        "data": [
          {
            "details": {
              "new": "libyaml v0.2.5 is vulnerable to Buffer Overflow. Affected by this issue is the function yaml_emitter_emit of the file /src/libyaml/src/emitter.c. The manipulation leads to a double-free. NOTE: this is disputed by the supplier because the discoverer's sample C code is incorrect: it does not call all of the required _initialize functions that are described in the LibYAML documentation.",
              "old": "libyaml v0.2.5 is vulnerable to Buffer Overflow. Affected by this issue is the function yaml_emitter_emit of the file /src/libyaml/src/emitter.c. The manipulation leads to a double-free."
            },
            "type": "description"
          },
          {
            "details": {
              "added": [
                "https://github.com/yaml/libyaml/issues/298",
                "https://github.com/yaml/libyaml/issues/302"
              ],
              "removed": []
            },
            "type": "references"
          }
        ],
        "id": "d0ec1635-fc53-4419-99fb-452cf3b091c0"
      },
      {
        "created": "2024-08-28T15:30:00+00:00",
        "data": [
          {
            "details": {
              "added": {},
              "removed": {
                "ssvc": {
                  "options": {
                    "Automatable": "no",
                    "Exploitation": "none",
                    "Technical Impact": "partial"
                  },
                  "version": "2.0.3"
                }
              },
              "updated": {}
            },
            "type": "metrics"
          }
        ],
        "id": "9f18c91c-ca47-47ef-98ea-65e2d3d4372a"
      },
      {
        "created": "2024-08-28T15:45:00+00:00",
        "data": [
          {
            "details": {
              "new": "DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: none. Reason: This candidate was withdrawn by its CNA. Further investigation showed that it was not a security issue. Notes: none.",
              "old": "libyaml v0.2.5 is vulnerable to Buffer Overflow. Affected by this issue is the function yaml_emitter_emit of the file /src/libyaml/src/emitter.c. The manipulation leads to a double-free. NOTE: this is disputed by the supplier because the discoverer's sample C code is incorrect: it does not call all of the required _initialize functions that are described in the LibYAML documentation."
            },
            "type": "description"
          }
        ],
        "id": "8b0cf9c2-bcc5-40ca-8030-5f684650360c"
      },
      {
        "created": "2024-08-28T16:45:00+00:00",
        "data": [
          {
            "details": {
              "added": [],
              "removed": [
                "CWE-787"
              ]
            },
            "type": "weaknesses"
          },
          {
            "details": {
              "added": [],
              "removed": [
                "cpe:2.3:a:pyyaml:libyaml:0.2.5:*:*:*:*:*:*:*"
              ]
            },
            "type": "cpes"
          },
          {
            "details": {
              "added": [],
              "removed": [
                "pyyaml",
                "pyyaml$PRODUCT$libyaml"
              ]
            },
            "type": "vendors"
          },
          {
            "details": {
              "added": [],
              "removed": [
                "https://github.com/idhyt/pocs/tree/main/libyaml",
                "https://github.com/yaml/libyaml/issues/298",
                "https://github.com/yaml/libyaml/issues/302"
              ]
            },
            "type": "references"
          },
          {
            "details": {
              "added": {},
              "removed": {},
              "updated": {
                "cvssV3_1": {
                  "new": {
                    "score": 6.5,
                    "vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
                  },
                  "old": {
                    "score": 9.8,
                    "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
                  }
                }
              }
            },
            "type": "metrics"
          }
        ],
        "id": "2aa165b9-10ad-460f-99dc-498ca92bee20"
      }
    ],
    "cpes": {
      "data": [],
      "providers": []
    },
    "created": {
      "data": "2024-06-13T00:00:00+00:00",
      "provider": "mitre"
    },
    "description": {
      "data": "DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: none. Reason: This candidate was withdrawn by its CNA. Further investigation showed that it was not a security issue. Notes: none.",
      "provider": "mitre"
    },
    "metrics": {
      "cvssV2_0": {
        "data": {},
        "provider": null
      },
      "cvssV3_0": {
        "data": {},
        "provider": null
      },
      "cvssV3_1": {
        "data": {
          "score": 6.5,
          "vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
        },
        "provider": "redhat"
      },
      "cvssV4_0": {
        "data": {},
        "provider": null
      },
      "kev": {
        "data": {},
        "provider": null
      },
      "ssvc": {
        "data": {},
        "provider": null
      },
      "threat_severity": {
        "data": "Moderate",
        "provider": "redhat"
      }
    },
    "references": {
      "data": [
        "https://github.com/idhyt/pocs/blob/main/libyaml/CVE-2024-35326.c",
        "https://nvd.nist.gov/vuln/detail/CVE-2024-35326",
        "https://www.cve.org/CVERecord?id=CVE-2024-35326"
      ],
      "providers": [
        "redhat"
      ]
    },
    "title": {
      "data": "libyaml: double-free in yaml_emitter_emit in /src/libyaml/src/emitter.c",
      "provider": "nvd"
    },
    "updated": {
      "data": "2024-08-28T16:15:08.740000+00:00",
      "provider": "nvd"
    },
    "vendors": {
      "data": [],
      "providers": []
    },
    "weaknesses": {
      "data": [
        "CWE-415"
      ],
      "providers": [
        "redhat"
      ]
    }
  },
  "redhat": {
    "cpes": [],
    "created": "2024-06-13T00:00:00+00:00",
    "description": "libyaml v0.2.5 is vulnerable to Buffer Overflow. Affected by this issue is the function yaml_emitter_emit of the file /src/libyaml/src/emitter.c. The manipulation leads to a double-free.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 6.5,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
      },
      "threat_severity": "Moderate"
    },
    "redhat_repo_path": "2024/CVE-2024-35326.json",
    "references": [
      "https://github.com/idhyt/pocs/blob/main/libyaml/CVE-2024-35326.c",
      "https://nvd.nist.gov/vuln/detail/CVE-2024-35326",
      "https://www.cve.org/CVERecord?id=CVE-2024-35326"
    ],
    "title": "libyaml: double-free in yaml_emitter_emit in /src/libyaml/src/emitter.c",
    "updated": "2024-06-13T00:00:00+00:00",
    "vendors": [],
    "weaknesses": [
      "CWE-415"
    ]
  },
  "vulnrichment": {
    "cpes": [],
    "created": "2024-06-13T00:00:00+00:00",
    "description": "DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: none. Reason: This candidate was withdrawn by its CNA. Further investigation showed that it was not a security issue. Notes: none.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {},
      "cvssV4_0": {},
      "kev": {},
      "ssvc": {}
    },
    "references": [],
    "title": null,
    "updated": "2024-08-28T15:38:17.799524+00:00",
    "vendors": [],
    "vulnrichment_repo_path": "2024/35xxx/CVE-2024-35326.json",
    "weaknesses": []
  }
}