{
  "cve": "CVE-2018-10998",
  "mitre": {
    "cpes": [],
    "created": "2018-05-12T04:00:00+00:00",
    "description": "An issue was discovered in Exiv2 0.26. readMetadata in jp2image.cpp allows remote attackers to cause a denial of service (SIGABRT) by triggering an incorrect Safe::add call.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {},
      "cvssV4_0": {}
    },
    "mitre_repo_path": "cves/2018/10xxx/CVE-2018-10998.json",
    "references": [
      "https://access.redhat.com/errata/RHSA-2019:2101",
      "https://github.com/Exiv2/exiv2/issues/303",
      "https://lists.debian.org/debian-lts-announce/2018/06/msg00010.html",
      "https://security.gentoo.org/glsa/201811-14",
      "https://usn.ubuntu.com/3700-1/",
      "https://www.debian.org/security/2018/dsa-4238"
    ],
    "title": null,
    "updated": "2024-08-05T07:54:36.371000+00:00",
    "vendors": [],
    "weaknesses": []
  },
  "nvd": {
    "cpes": [
      "cpe:2.3:a:exiv2:exiv2:0.26:*:*:*:*:*:*:*",
      "cpe:2.3:o:canonical:ubuntu_linux:14.04:*:*:*:lts:*:*:*",
      "cpe:2.3:o:canonical:ubuntu_linux:16.04:*:*:*:lts:*:*:*",
      "cpe:2.3:o:canonical:ubuntu_linux:17.10:*:*:*:*:*:*:*",
      "cpe:2.3:o:canonical:ubuntu_linux:18.04:*:*:*:lts:*:*:*",
      "cpe:2.3:o:debian:debian_linux:8.0:*:*:*:*:*:*:*",
      "cpe:2.3:o:debian:debian_linux:9.0:*:*:*:*:*:*:*",
      "cpe:2.3:o:redhat:enterprise_linux_desktop:7.0:*:*:*:*:*:*:*",
      "cpe:2.3:o:redhat:enterprise_linux_server:7.0:*:*:*:*:*:*:*",
      "cpe:2.3:o:redhat:enterprise_linux_workstation:7.0:*:*:*:*:*:*:*"
    ],
    "created": "2018-05-12T04:29:00.270000+00:00",
    "description": "An issue was discovered in Exiv2 0.26. readMetadata in jp2image.cpp allows remote attackers to cause a denial of service (SIGABRT) by triggering an incorrect Safe::add call.",
    "metrics": {
      "cvssV2_0": {
        "score": 4.3,
        "vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P"
      },
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 6.5,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
      },
      "cvssV4_0": {}
    },
    "nvd_repo_path": "2018/CVE-2018-10998.json",
    "references": [
      "https://access.redhat.com/errata/RHSA-2019:2101",
      "https://github.com/Exiv2/exiv2/issues/303",
      "https://lists.debian.org/debian-lts-announce/2018/06/msg00010.html",
      "https://security.gentoo.org/glsa/201811-14",
      "https://usn.ubuntu.com/3700-1/",
      "https://www.debian.org/security/2018/dsa-4238"
    ],
    "title": null,
    "updated": "2023-03-01T17:13:13.523000+00:00",
    "vendors": [
      "canonical",
      "canonical$PRODUCT$ubuntu_linux",
      "debian",
      "debian$PRODUCT$debian_linux",
      "exiv2",
      "exiv2$PRODUCT$exiv2",
      "redhat",
      "redhat$PRODUCT$enterprise_linux_desktop",
      "redhat$PRODUCT$enterprise_linux_server",
      "redhat$PRODUCT$enterprise_linux_workstation"
    ],
    "weaknesses": [
      "NVD-CWE-noinfo"
    ]
  },
  "opencve": {
    "changes": [],
    "cpes": {
      "data": [
        "cpe:/o:redhat:enterprise_linux:7",
        "cpe:2.3:a:exiv2:exiv2:0.26:*:*:*:*:*:*:*",
        "cpe:2.3:o:canonical:ubuntu_linux:14.04:*:*:*:lts:*:*:*",
        "cpe:2.3:o:canonical:ubuntu_linux:16.04:*:*:*:lts:*:*:*",
        "cpe:2.3:o:canonical:ubuntu_linux:17.10:*:*:*:*:*:*:*",
        "cpe:2.3:o:canonical:ubuntu_linux:18.04:*:*:*:lts:*:*:*",
        "cpe:2.3:o:debian:debian_linux:8.0:*:*:*:*:*:*:*",
        "cpe:2.3:o:debian:debian_linux:9.0:*:*:*:*:*:*:*",
        "cpe:2.3:o:redhat:enterprise_linux_desktop:7.0:*:*:*:*:*:*:*",
        "cpe:2.3:o:redhat:enterprise_linux_server:7.0:*:*:*:*:*:*:*",
        "cpe:2.3:o:redhat:enterprise_linux_workstation:7.0:*:*:*:*:*:*:*"
      ],
      "providers": [
        "nvd",
        "redhat"
      ]
    },
    "created": {
      "data": "2018-05-09T00:00:00+00:00",
      "provider": "redhat"
    },
    "description": {
      "data": "An issue was discovered in Exiv2 0.26. readMetadata in jp2image.cpp allows remote attackers to cause a denial of service (SIGABRT) by triggering an incorrect Safe::add call.",
      "provider": "mitre"
    },
    "metrics": {
      "cvssV2_0": {
        "data": {
          "score": 4.3,
          "vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P"
        },
        "provider": "nvd"
      },
      "cvssV3_0": {
        "data": {
          "score": 3.3,
          "vector": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:L"
        },
        "provider": "redhat"
      },
      "cvssV3_1": {
        "data": {
          "score": 6.5,
          "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
        },
        "provider": "nvd"
      },
      "cvssV4_0": {
        "data": {},
        "provider": null
      },
      "kev": {
        "data": {},
        "provider": null
      },
      "ssvc": {
        "data": {},
        "provider": null
      },
      "threat_severity": {
        "data": "Low",
        "provider": "redhat"
      }
    },
    "references": {
      "data": [
        "https://access.redhat.com/errata/RHSA-2019:2101",
        "https://github.com/Exiv2/exiv2/issues/303",
        "https://lists.debian.org/debian-lts-announce/2018/06/msg00010.html",
        "https://nvd.nist.gov/vuln/detail/CVE-2018-10998",
        "https://security.gentoo.org/glsa/201811-14",
        "https://usn.ubuntu.com/3700-1/",
        "https://www.cve.org/CVERecord?id=CVE-2018-10998",
        "https://www.debian.org/security/2018/dsa-4238"
      ],
      "providers": [
        "mitre",
        "nvd",
        "redhat"
      ]
    },
    "title": {
      "data": "exiv2: SIGABRT by triggering an incorrect Safe::add call",
      "provider": "nvd"
    },
    "updated": {
      "data": "2024-08-05T07:54:36.371000+00:00",
      "provider": "mitre"
    },
    "vendors": {
      "data": [
        "canonical",
        "canonical$PRODUCT$ubuntu_linux",
        "debian",
        "debian$PRODUCT$debian_linux",
        "exiv2",
        "exiv2$PRODUCT$exiv2",
        "redhat",
        "redhat$PRODUCT$enterprise_linux",
        "redhat$PRODUCT$enterprise_linux_desktop",
        "redhat$PRODUCT$enterprise_linux_server",
        "redhat$PRODUCT$enterprise_linux_workstation"
      ],
      "providers": [
        "nvd",
        "redhat"
      ]
    },
    "weaknesses": {
      "data": [
        "CWE-400",
        "NVD-CWE-noinfo"
      ],
      "providers": [
        "nvd",
        "redhat"
      ]
    }
  },
  "redhat": {
    "cpes": [
      "cpe:/o:redhat:enterprise_linux:7"
    ],
    "created": "2018-05-09T00:00:00+00:00",
    "description": "An issue was discovered in Exiv2 0.26. readMetadata in jp2image.cpp allows remote attackers to cause a denial of service (SIGABRT) by triggering an incorrect Safe::add call.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {
        "score": 3.3,
        "vector": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:L"
      },
      "cvssV3_1": {},
      "threat_severity": "Low"
    },
    "redhat_repo_path": "2018/CVE-2018-10998.json",
    "references": [
      "https://nvd.nist.gov/vuln/detail/CVE-2018-10998",
      "https://www.cve.org/CVERecord?id=CVE-2018-10998"
    ],
    "title": "exiv2: SIGABRT by triggering an incorrect Safe::add call",
    "updated": "2018-05-09T00:00:00+00:00",
    "vendors": [
      "redhat",
      "redhat$PRODUCT$enterprise_linux"
    ],
    "weaknesses": [
      "CWE-400"
    ]
  }
}