{
  "cve": "CVE-2022-40898",
  "mitre": {
    "cpes": [],
    "created": "2022-12-22T00:00:00+00:00",
    "description": "An issue discovered in Python Packaging Authority (PyPA) Wheel 0.37.1 and earlier allows remote attackers to cause a denial of service via attacker controlled input to wheel cli.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {},
      "cvssV4_0": {}
    },
    "mitre_repo_path": "cves/2022/40xxx/CVE-2022-40898.json",
    "references": [
      "https://github.com/pypa/wheel/blob/main/src/wheel/wheelfile.py#L18",
      "https://pypi.org/project/wheel/",
      "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/"
    ],
    "title": null,
    "updated": "2024-08-03T12:28:42.936000+00:00",
    "vendors": [],
    "weaknesses": []
  },
  "nvd": {
    "cpes": [
      "cpe:2.3:a:wheel_project:wheel:*:*:*:*:*:python:*:*"
    ],
    "created": "2022-12-23T00:15:14.043000+00:00",
    "description": "An issue discovered in Python Packaging Authority (PyPA) Wheel 0.37.1 and earlier allows remote attackers to cause a denial of service via attacker controlled input to wheel cli.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 7.5,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
      },
      "cvssV4_0": {}
    },
    "nvd_repo_path": "2022/CVE-2022-40898.json",
    "references": [
      "https://github.com/pypa/wheel/blob/main/src/wheel/wheelfile.py#L18",
      "https://pypi.org/project/wheel/",
      "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/"
    ],
    "title": null,
    "updated": "2022-12-30T22:15:22.800000+00:00",
    "vendors": [
      "wheel_project",
      "wheel_project$PRODUCT$wheel"
    ],
    "weaknesses": [
      "NVD-CWE-noinfo"
    ]
  },
  "opencve": {
    "changes": [],
    "cpes": {
      "data": [
        "cpe:/a:redhat:enterprise_linux:9::crb",
        "cpe:/a:redhat:rhel_software_collections:3::el7",
        "cpe:2.3:a:wheel_project:wheel:*:*:*:*:*:python:*:*"
      ],
      "providers": [
        "nvd",
        "redhat"
      ]
    },
    "created": {
      "data": "2022-12-21T00:00:00+00:00",
      "provider": "redhat"
    },
    "description": {
      "data": "An issue discovered in Python Packaging Authority (PyPA) Wheel 0.37.1 and earlier allows remote attackers to cause a denial of service via attacker controlled input to wheel cli.",
      "provider": "mitre"
    },
    "metrics": {
      "cvssV2_0": {
        "data": {},
        "provider": null
      },
      "cvssV3_0": {
        "data": {},
        "provider": null
      },
      "cvssV3_1": {
        "data": {
          "score": 7.5,
          "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
        },
        "provider": "nvd"
      },
      "cvssV4_0": {
        "data": {},
        "provider": null
      },
      "kev": {
        "data": {},
        "provider": null
      },
      "ssvc": {
        "data": {},
        "provider": null
      },
      "threat_severity": {
        "data": "Moderate",
        "provider": "redhat"
      }
    },
    "references": {
      "data": [
        "https://github.com/pypa/wheel/blob/main/src/wheel/wheelfile.py#L18",
        "https://nvd.nist.gov/vuln/detail/CVE-2022-40898",
        "https://pypi.org/project/wheel/",
        "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/",
        "https://www.cve.org/CVERecord?id=CVE-2022-40898"
      ],
      "providers": [
        "mitre",
        "nvd",
        "redhat"
      ]
    },
    "title": {
      "data": "python-wheel: remote attackers can cause denial of service via attacker controlled input to wheel cli",
      "provider": "nvd"
    },
    "updated": {
      "data": "2024-08-03T12:28:42.936000+00:00",
      "provider": "mitre"
    },
    "vendors": {
      "data": [
        "redhat",
        "redhat$PRODUCT$enterprise_linux",
        "redhat$PRODUCT$rhel_software_collections",
        "wheel_project",
        "wheel_project$PRODUCT$wheel"
      ],
      "providers": [
        "nvd",
        "redhat"
      ]
    },
    "weaknesses": {
      "data": [
        "CWE-400",
        "NVD-CWE-noinfo"
      ],
      "providers": [
        "nvd",
        "redhat"
      ]
    }
  },
  "redhat": {
    "cpes": [
      "cpe:/a:redhat:enterprise_linux:9::crb",
      "cpe:/a:redhat:rhel_software_collections:3::el7"
    ],
    "created": "2022-12-21T00:00:00+00:00",
    "description": "An issue discovered in Python Packaging Authority (PyPA) Wheel 0.37.1 and earlier allows remote attackers to cause a denial of service via attacker controlled input to wheel cli.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 7.5,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
      },
      "threat_severity": "Moderate"
    },
    "redhat_repo_path": "2022/CVE-2022-40898.json",
    "references": [
      "https://nvd.nist.gov/vuln/detail/CVE-2022-40898",
      "https://www.cve.org/CVERecord?id=CVE-2022-40898"
    ],
    "title": "python-wheel: remote attackers can cause denial of service via attacker controlled input to wheel cli",
    "updated": "2022-12-21T00:00:00+00:00",
    "vendors": [
      "redhat",
      "redhat$PRODUCT$enterprise_linux",
      "redhat$PRODUCT$rhel_software_collections"
    ],
    "weaknesses": [
      "CWE-400"
    ]
  }
}