{
  "cve": "CVE-2021-22193",
  "mitre": {
    "cpes": [],
    "created": "2021-03-24T16:57:47+00:00",
    "description": "An issue has been discovered in GitLab affecting all versions starting with 7.1. A member of a private group was able to validate the use of a specific name for private project.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 3.5,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:L/I:N/A:N"
      },
      "cvssV4_0": {}
    },
    "mitre_repo_path": "cves/2021/22xxx/CVE-2021-22193.json",
    "references": [
      "https://gitlab.com/gitlab-org/cves/-/blob/master/2021/CVE-2021-22193.json",
      "https://gitlab.com/gitlab-org/gitlab/-/issues/12560",
      "https://hackerone.com/reports/605608"
    ],
    "title": null,
    "updated": "2024-08-03T18:37:18.311000+00:00",
    "vendors": [],
    "weaknesses": []
  },
  "nvd": {
    "cpes": [
      "cpe:2.3:a:gitlab:gitlab:*:*:*:*:community:*:*:*",
      "cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*"
    ],
    "created": "2021-03-24T17:15:14.260000+00:00",
    "description": "An issue has been discovered in GitLab affecting all versions starting with 7.1. A member of a private group was able to validate the use of a specific name for private project.",
    "metrics": {
      "cvssV2_0": {
        "score": 3.5,
        "vector": "AV:N/AC:M/Au:S/C:P/I:N/A:N"
      },
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 3.5,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:L/I:N/A:N"
      },
      "cvssV4_0": {}
    },
    "nvd_repo_path": "2021/CVE-2021-22193.json",
    "references": [
      "https://gitlab.com/gitlab-org/cves/-/blob/master/2021/CVE-2021-22193.json",
      "https://gitlab.com/gitlab-org/gitlab/-/issues/12560",
      "https://hackerone.com/reports/605608"
    ],
    "title": null,
    "updated": "2021-03-26T16:24:06.683000+00:00",
    "vendors": [
      "gitlab",
      "gitlab$PRODUCT$gitlab"
    ],
    "weaknesses": [
      "CWE-209"
    ]
  },
  "opencve": {
    "changes": [],
    "cpes": {
      "data": [
        "cpe:2.3:a:gitlab:gitlab:*:*:*:*:community:*:*:*",
        "cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*"
      ],
      "providers": [
        "nvd"
      ]
    },
    "created": {
      "data": "2021-03-24T16:57:47+00:00",
      "provider": "mitre"
    },
    "description": {
      "data": "An issue has been discovered in GitLab affecting all versions starting with 7.1. A member of a private group was able to validate the use of a specific name for private project.",
      "provider": "mitre"
    },
    "metrics": {
      "cvssV2_0": {
        "data": {
          "score": 3.5,
          "vector": "AV:N/AC:M/Au:S/C:P/I:N/A:N"
        },
        "provider": "nvd"
      },
      "cvssV3_0": {
        "data": {},
        "provider": null
      },
      "cvssV3_1": {
        "data": {
          "score": 3.5,
          "vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:L/I:N/A:N"
        },
        "provider": "mitre"
      },
      "cvssV4_0": {
        "data": {},
        "provider": null
      },
      "kev": {
        "data": {},
        "provider": null
      },
      "ssvc": {
        "data": {},
        "provider": null
      },
      "threat_severity": {
        "data": null,
        "provider": null
      }
    },
    "references": {
      "data": [
        "https://gitlab.com/gitlab-org/cves/-/blob/master/2021/CVE-2021-22193.json",
        "https://gitlab.com/gitlab-org/gitlab/-/issues/12560",
        "https://hackerone.com/reports/605608"
      ],
      "providers": [
        "mitre",
        "nvd"
      ]
    },
    "title": {
      "data": null,
      "provider": null
    },
    "updated": {
      "data": "2024-08-03T18:37:18.311000+00:00",
      "provider": "mitre"
    },
    "vendors": {
      "data": [
        "gitlab",
        "gitlab$PRODUCT$gitlab"
      ],
      "providers": [
        "nvd"
      ]
    },
    "weaknesses": {
      "data": [
        "CWE-209"
      ],
      "providers": [
        "nvd"
      ]
    }
  }
}