{
  "cve": "CVE-2021-33840",
  "mitre": {
    "cpes": [],
    "created": "2021-06-03T23:57:32+00:00",
    "description": "The server in Luca through 1.1.14 allows remote attackers to cause a denial of service (insertion of many fake records related to COVID-19) because Phone Number data lacks a digital signature.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {},
      "cvssV4_0": {}
    },
    "mitre_repo_path": "cves/2021/33xxx/CVE-2021-33840.json",
    "references": [
      "https://gitlab.com/lucaapp/web/-/issues/1#note_560963608",
      "https://luca-app.de/securityoverview/processes/guest_registration.html#verifying-the-contact-data"
    ],
    "title": null,
    "updated": "2024-08-03T23:58:23.224000+00:00",
    "vendors": [],
    "weaknesses": []
  },
  "nvd": {
    "cpes": [
      "cpe:2.3:a:luca-app:luca:*:*:*:*:*:android:*:*"
    ],
    "created": "2021-06-04T00:15:07.410000+00:00",
    "description": "The server in Luca through 1.1.14 allows remote attackers to cause a denial of service (insertion of many fake records related to COVID-19) because Phone Number data lacks a digital signature.",
    "metrics": {
      "cvssV2_0": {
        "score": 5.0,
        "vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
      },
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 7.5,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
      },
      "cvssV4_0": {}
    },
    "nvd_repo_path": "2021/CVE-2021-33840.json",
    "references": [
      "https://gitlab.com/lucaapp/web/-/issues/1#note_560963608",
      "https://luca-app.de/securityoverview/processes/guest_registration.html#verifying-the-contact-data"
    ],
    "title": null,
    "updated": "2022-07-12T17:42:04.277000+00:00",
    "vendors": [
      "luca-app",
      "luca-app$PRODUCT$luca"
    ],
    "weaknesses": [
      "CWE-345"
    ]
  },
  "opencve": {
    "changes": [],
    "cpes": {
      "data": [
        "cpe:2.3:a:luca-app:luca:*:*:*:*:*:android:*:*"
      ],
      "providers": [
        "nvd"
      ]
    },
    "created": {
      "data": "2021-06-03T23:57:32+00:00",
      "provider": "mitre"
    },
    "description": {
      "data": "The server in Luca through 1.1.14 allows remote attackers to cause a denial of service (insertion of many fake records related to COVID-19) because Phone Number data lacks a digital signature.",
      "provider": "mitre"
    },
    "metrics": {
      "cvssV2_0": {
        "data": {
          "score": 5.0,
          "vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
        },
        "provider": "nvd"
      },
      "cvssV3_0": {
        "data": {},
        "provider": null
      },
      "cvssV3_1": {
        "data": {
          "score": 7.5,
          "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
        },
        "provider": "nvd"
      },
      "cvssV4_0": {
        "data": {},
        "provider": null
      },
      "kev": {
        "data": {},
        "provider": null
      },
      "ssvc": {
        "data": {},
        "provider": null
      },
      "threat_severity": {
        "data": null,
        "provider": null
      }
    },
    "references": {
      "data": [
        "https://gitlab.com/lucaapp/web/-/issues/1#note_560963608",
        "https://luca-app.de/securityoverview/processes/guest_registration.html#verifying-the-contact-data"
      ],
      "providers": [
        "mitre",
        "nvd"
      ]
    },
    "title": {
      "data": null,
      "provider": null
    },
    "updated": {
      "data": "2024-08-03T23:58:23.224000+00:00",
      "provider": "mitre"
    },
    "vendors": {
      "data": [
        "luca-app",
        "luca-app$PRODUCT$luca"
      ],
      "providers": [
        "nvd"
      ]
    },
    "weaknesses": {
      "data": [
        "CWE-345"
      ],
      "providers": [
        "nvd"
      ]
    }
  }
}