{
  "cve": "CVE-2021-38958",
  "mitre": {
    "cpes": [],
    "created": "2021-11-30T16:45:15.183527+00:00",
    "description": "IBM MQ Appliance 9.2 CD and 9.2 LTS is affected by a denial of service attack caused by a concurrency issue. IBM X-Force ID: 212042",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {
        "score": 5.1,
        "vector": "CVSS:3.0/S:U/UI:N/A:H/I:N/C:N/AV:L/PR:N/AC:H/RC:C/E:U/RL:O"
      },
      "cvssV3_1": {},
      "cvssV4_0": {}
    },
    "mitre_repo_path": "cves/2021/38xxx/CVE-2021-38958.json",
    "references": [
      "https://exchange.xforce.ibmcloud.com/vulnerabilities/212043",
      "https://www.ibm.com/support/pages/node/6519420"
    ],
    "title": null,
    "updated": "2024-09-16T20:16:24.685000+00:00",
    "vendors": [],
    "weaknesses": []
  },
  "nvd": {
    "cpes": [
      "cpe:2.3:a:ibm:mq_appliance:9.2.0.0:*:*:*:continuous_delivery:*:*:*",
      "cpe:2.3:a:ibm:mq_appliance:9.2.0.0:*:*:*:lts:*:*:*"
    ],
    "created": "2021-11-30T17:15:11.427000+00:00",
    "description": "IBM MQ Appliance 9.2 CD and 9.2 LTS is affected by a denial of service attack caused by a concurrency issue. IBM X-Force ID: 212042",
    "metrics": {
      "cvssV2_0": {
        "score": 2.1,
        "vector": "AV:L/AC:L/Au:N/C:N/I:N/A:P"
      },
      "cvssV3_0": {
        "score": 5.1,
        "vector": "CVSS:3.0/AV:L/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H"
      },
      "cvssV3_1": {
        "score": 5.5,
        "vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
      },
      "cvssV4_0": {}
    },
    "nvd_repo_path": "2021/CVE-2021-38958.json",
    "references": [
      "https://exchange.xforce.ibmcloud.com/vulnerabilities/212043",
      "https://www.ibm.com/support/pages/node/6519420"
    ],
    "title": null,
    "updated": "2021-11-30T20:32:18.963000+00:00",
    "vendors": [
      "ibm",
      "ibm$PRODUCT$mq_appliance"
    ],
    "weaknesses": [
      "NVD-CWE-noinfo"
    ]
  },
  "opencve": {
    "changes": [],
    "cpes": {
      "data": [
        "cpe:2.3:a:ibm:mq_appliance:9.2.0.0:*:*:*:continuous_delivery:*:*:*",
        "cpe:2.3:a:ibm:mq_appliance:9.2.0.0:*:*:*:lts:*:*:*"
      ],
      "providers": [
        "nvd"
      ]
    },
    "created": {
      "data": "2021-11-30T16:45:15.183527+00:00",
      "provider": "mitre"
    },
    "description": {
      "data": "IBM MQ Appliance 9.2 CD and 9.2 LTS is affected by a denial of service attack caused by a concurrency issue. IBM X-Force ID: 212042",
      "provider": "mitre"
    },
    "metrics": {
      "cvssV2_0": {
        "data": {
          "score": 2.1,
          "vector": "AV:L/AC:L/Au:N/C:N/I:N/A:P"
        },
        "provider": "nvd"
      },
      "cvssV3_0": {
        "data": {
          "score": 5.1,
          "vector": "CVSS:3.0/S:U/UI:N/A:H/I:N/C:N/AV:L/PR:N/AC:H/RC:C/E:U/RL:O"
        },
        "provider": "mitre"
      },
      "cvssV3_1": {
        "data": {
          "score": 5.5,
          "vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
        },
        "provider": "nvd"
      },
      "cvssV4_0": {
        "data": {},
        "provider": null
      },
      "kev": {
        "data": {},
        "provider": null
      },
      "ssvc": {
        "data": {},
        "provider": null
      },
      "threat_severity": {
        "data": null,
        "provider": null
      }
    },
    "references": {
      "data": [
        "https://exchange.xforce.ibmcloud.com/vulnerabilities/212043",
        "https://www.ibm.com/support/pages/node/6519420"
      ],
      "providers": [
        "mitre",
        "nvd"
      ]
    },
    "title": {
      "data": null,
      "provider": null
    },
    "updated": {
      "data": "2024-09-16T20:16:24.685000+00:00",
      "provider": "mitre"
    },
    "vendors": {
      "data": [
        "ibm",
        "ibm$PRODUCT$mq_appliance"
      ],
      "providers": [
        "nvd"
      ]
    },
    "weaknesses": {
      "data": [
        "NVD-CWE-noinfo"
      ],
      "providers": [
        "nvd"
      ]
    }
  }
}