{
  "cve": "CVE-2008-1721",
  "mitre": {
    "cpes": [],
    "created": "2008-04-10T19:00:00+00:00",
    "description": "Integer signedness error in the zlib extension module in Python 2.5.2 and earlier allows remote attackers to execute arbitrary code via a negative signed integer, which triggers insufficient memory allocation and a buffer overflow.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {},
      "cvssV4_0": {}
    },
    "mitre_repo_path": "cves/2008/1xxx/CVE-2008-1721.json",
    "references": [
      "http://bugs.python.org/issue2586",
      "http://lists.apple.com/archives/security-announce/2009/Feb/msg00000.html",
      "http://secunia.com/advisories/29889",
      "http://secunia.com/advisories/29955",
      "http://secunia.com/advisories/30872",
      "http://secunia.com/advisories/31255",
      "http://secunia.com/advisories/31358",
      "http://secunia.com/advisories/31365",
      "http://secunia.com/advisories/33937",
      "http://secunia.com/advisories/37471",
      "http://secunia.com/advisories/38675",
      "http://security.gentoo.org/glsa/glsa-200807-01.xml",
      "http://securityreason.com/securityalert/3802",
      "http://slackware.com/security/viewer.php?l=slackware-security&y=2008&m=slackware-security.525289",
      "http://support.apple.com/kb/HT3438",
      "http://support.avaya.com/css/P8/documents/100074697",
      "http://wiki.rpath.com/wiki/Advisories:rPSA-2008-0149",
      "http://www.debian.org/security/2008/dsa-1551",
      "http://www.debian.org/security/2008/dsa-1620",
      "http://www.mandriva.com/security/advisories?name=MDVSA-2008:085",
      "http://www.securityfocus.com/archive/1/490690/100/0/threaded",
      "http://www.securityfocus.com/archive/1/507985/100/0/threaded",
      "http://www.securityfocus.com/bid/28715",
      "http://www.securitytracker.com/id?1019823",
      "http://www.ubuntu.com/usn/usn-632-1",
      "http://www.vmware.com/security/advisories/VMSA-2009-0016.html",
      "http://www.vupen.com/english/advisories/2008/1229/references",
      "http://www.vupen.com/english/advisories/2009/3316",
      "https://exchange.xforce.ibmcloud.com/vulnerabilities/41748",
      "https://issues.rpath.com/browse/RPL-2444",
      "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A8249",
      "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A8494",
      "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A9407"
    ],
    "title": null,
    "updated": "2024-08-07T08:32:01.129000+00:00",
    "vendors": [],
    "weaknesses": []
  },
  "nvd": {
    "cpes": [
      "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
      "cpe:2.3:o:canonical:ubuntu_linux:6.06:*:*:*:*:*:*:*",
      "cpe:2.3:o:canonical:ubuntu_linux:7.04:*:*:*:*:*:*:*",
      "cpe:2.3:o:canonical:ubuntu_linux:7.10:*:*:*:*:*:*:*",
      "cpe:2.3:o:canonical:ubuntu_linux:8.04:*:*:*:-:*:*:*",
      "cpe:2.3:o:debian:debian_linux:4.0:*:*:*:*:*:*:*"
    ],
    "created": "2008-04-10T19:05:00+00:00",
    "description": "Integer signedness error in the zlib extension module in Python 2.5.2 and earlier allows remote attackers to execute arbitrary code via a negative signed integer, which triggers insufficient memory allocation and a buffer overflow.",
    "metrics": {
      "cvssV2_0": {
        "score": 7.5,
        "vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P"
      },
      "cvssV3_0": {},
      "cvssV3_1": {},
      "cvssV4_0": {}
    },
    "nvd_repo_path": "2008/CVE-2008-1721.json",
    "references": [
      "http://bugs.python.org/issue2586",
      "http://lists.apple.com/archives/security-announce/2009/Feb/msg00000.html",
      "http://secunia.com/advisories/29889",
      "http://secunia.com/advisories/29955",
      "http://secunia.com/advisories/30872",
      "http://secunia.com/advisories/31255",
      "http://secunia.com/advisories/31358",
      "http://secunia.com/advisories/31365",
      "http://secunia.com/advisories/33937",
      "http://secunia.com/advisories/37471",
      "http://secunia.com/advisories/38675",
      "http://security.gentoo.org/glsa/glsa-200807-01.xml",
      "http://securityreason.com/securityalert/3802",
      "http://slackware.com/security/viewer.php?l=slackware-security&y=2008&m=slackware-security.525289",
      "http://support.apple.com/kb/HT3438",
      "http://support.avaya.com/css/P8/documents/100074697",
      "http://wiki.rpath.com/wiki/Advisories:rPSA-2008-0149",
      "http://www.debian.org/security/2008/dsa-1551",
      "http://www.debian.org/security/2008/dsa-1620",
      "http://www.mandriva.com/security/advisories?name=MDVSA-2008:085",
      "http://www.securityfocus.com/archive/1/490690/100/0/threaded",
      "http://www.securityfocus.com/archive/1/507985/100/0/threaded",
      "http://www.securityfocus.com/bid/28715",
      "http://www.securitytracker.com/id?1019823",
      "http://www.ubuntu.com/usn/usn-632-1",
      "http://www.vmware.com/security/advisories/VMSA-2009-0016.html",
      "http://www.vupen.com/english/advisories/2008/1229/references",
      "http://www.vupen.com/english/advisories/2009/3316",
      "https://exchange.xforce.ibmcloud.com/vulnerabilities/41748",
      "https://issues.rpath.com/browse/RPL-2444",
      "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A8249",
      "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A8494",
      "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A9407"
    ],
    "title": null,
    "updated": "2022-07-05T18:43:52.637000+00:00",
    "vendors": [
      "canonical",
      "canonical$PRODUCT$ubuntu_linux",
      "debian",
      "debian$PRODUCT$debian_linux",
      "python",
      "python$PRODUCT$python"
    ],
    "weaknesses": [
      "CWE-681"
    ]
  },
  "opencve": {
    "changes": [],
    "cpes": {
      "data": [
        "cpe:/o:redhat:enterprise_linux:4",
        "cpe:/o:redhat:enterprise_linux:5",
        "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
        "cpe:2.3:o:canonical:ubuntu_linux:6.06:*:*:*:*:*:*:*",
        "cpe:2.3:o:canonical:ubuntu_linux:7.04:*:*:*:*:*:*:*",
        "cpe:2.3:o:canonical:ubuntu_linux:7.10:*:*:*:*:*:*:*",
        "cpe:2.3:o:canonical:ubuntu_linux:8.04:*:*:*:-:*:*:*",
        "cpe:2.3:o:debian:debian_linux:4.0:*:*:*:*:*:*:*"
      ],
      "providers": [
        "nvd",
        "redhat"
      ]
    },
    "created": {
      "data": "2008-04-09T00:00:00+00:00",
      "provider": "redhat"
    },
    "description": {
      "data": "Integer signedness error in the zlib extension module in Python 2.5.2 and earlier allows remote attackers to execute arbitrary code via a negative signed integer, which triggers insufficient memory allocation and a buffer overflow.",
      "provider": "mitre"
    },
    "metrics": {
      "cvssV2_0": {
        "data": {
          "score": 7.5,
          "vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P"
        },
        "provider": "nvd"
      },
      "cvssV3_0": {
        "data": {},
        "provider": null
      },
      "cvssV3_1": {
        "data": {},
        "provider": null
      },
      "cvssV4_0": {
        "data": {},
        "provider": null
      },
      "kev": {
        "data": {},
        "provider": null
      },
      "ssvc": {
        "data": {},
        "provider": null
      },
      "threat_severity": {
        "data": "Low",
        "provider": "redhat"
      }
    },
    "references": {
      "data": [
        "http://bugs.python.org/issue2586",
        "http://lists.apple.com/archives/security-announce/2009/Feb/msg00000.html",
        "http://secunia.com/advisories/29889",
        "http://secunia.com/advisories/29955",
        "http://secunia.com/advisories/30872",
        "http://secunia.com/advisories/31255",
        "http://secunia.com/advisories/31358",
        "http://secunia.com/advisories/31365",
        "http://secunia.com/advisories/33937",
        "http://secunia.com/advisories/37471",
        "http://secunia.com/advisories/38675",
        "http://security.gentoo.org/glsa/glsa-200807-01.xml",
        "http://securityreason.com/securityalert/3802",
        "http://slackware.com/security/viewer.php?l=slackware-security&y=2008&m=slackware-security.525289",
        "http://support.apple.com/kb/HT3438",
        "http://support.avaya.com/css/P8/documents/100074697",
        "http://wiki.rpath.com/wiki/Advisories:rPSA-2008-0149",
        "http://www.debian.org/security/2008/dsa-1551",
        "http://www.debian.org/security/2008/dsa-1620",
        "http://www.mandriva.com/security/advisories?name=MDVSA-2008:085",
        "http://www.securityfocus.com/archive/1/490690/100/0/threaded",
        "http://www.securityfocus.com/archive/1/507985/100/0/threaded",
        "http://www.securityfocus.com/bid/28715",
        "http://www.securitytracker.com/id?1019823",
        "http://www.ubuntu.com/usn/usn-632-1",
        "http://www.vmware.com/security/advisories/VMSA-2009-0016.html",
        "http://www.vupen.com/english/advisories/2008/1229/references",
        "http://www.vupen.com/english/advisories/2009/3316",
        "https://exchange.xforce.ibmcloud.com/vulnerabilities/41748",
        "https://issues.rpath.com/browse/RPL-2444",
        "https://nvd.nist.gov/vuln/detail/CVE-2008-1721",
        "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A8249",
        "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A8494",
        "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A9407",
        "https://www.cve.org/CVERecord?id=CVE-2008-1721"
      ],
      "providers": [
        "mitre",
        "nvd",
        "redhat"
      ]
    },
    "title": {
      "data": "python: integer signedness error in the zlib extension module",
      "provider": "nvd"
    },
    "updated": {
      "data": "2024-08-07T08:32:01.129000+00:00",
      "provider": "mitre"
    },
    "vendors": {
      "data": [
        "canonical",
        "canonical$PRODUCT$ubuntu_linux",
        "debian",
        "debian$PRODUCT$debian_linux",
        "python",
        "python$PRODUCT$python",
        "redhat",
        "redhat$PRODUCT$enterprise_linux"
      ],
      "providers": [
        "nvd",
        "redhat"
      ]
    },
    "weaknesses": {
      "data": [
        "CWE-681"
      ],
      "providers": [
        "nvd"
      ]
    }
  },
  "redhat": {
    "cpes": [
      "cpe:/o:redhat:enterprise_linux:4",
      "cpe:/o:redhat:enterprise_linux:5"
    ],
    "created": "2008-04-09T00:00:00+00:00",
    "description": "Integer signedness error in the zlib extension module in Python 2.5.2 and earlier allows remote attackers to execute arbitrary code via a negative signed integer, which triggers insufficient memory allocation and a buffer overflow.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {},
      "threat_severity": "Low"
    },
    "redhat_repo_path": "2008/CVE-2008-1721.json",
    "references": [
      "https://nvd.nist.gov/vuln/detail/CVE-2008-1721",
      "https://www.cve.org/CVERecord?id=CVE-2008-1721"
    ],
    "title": "python: integer signedness error in the zlib extension module",
    "updated": "2008-04-09T00:00:00+00:00",
    "vendors": [
      "redhat",
      "redhat$PRODUCT$enterprise_linux"
    ],
    "weaknesses": []
  }
}